#!/bin/bash
#
# Copyright 2024 Myco_rProbe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# =============================================================================
#
# Myco_rProbe - Probe evaluation pipeline
#
# This script evaluates the performance of designed rRNA probes against
# RNA-seq data. It performs the following steps:
#   1. Quality control with fastp
#   2. rRNA mapping with Bowtie2
#   3. Genome mapping for background evaluation
#   4. Coverage visualization with R
#
# Usage:
#   bash myco_rprobe_evaluate.sh -g <genome_mapping_list> -r <rrna_dir> \
#                                 -t <threads> -o <output_dir> -m <mirror_path>
#
# Author: Myco_rProbe Team
# Date:   2024
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Display help information
#
# Prints usage guide with required and optional arguments.
#
# Globals:
#   $0 - script name
# Returns:
#   None (exits with code 1)
# -----------------------------------------------------------------------------
usage() {
    cat << EOF
Usage: bash $0 -g <genome_mapping_list> -r <rrna_dir> -t <threads> -o <output_dir> -m <mirror_path>

Required arguments:
  -g <genome_mapping_list>    Path to genome mapping list (TSV:
                              strain<TAB>prefix<TAB>R1<TAB>R2<TAB>genome<TAB>gtf).
                              Example: 'example/batch_lib_config.tsv'
  -r <rrna_dir>               Path to directory containing rRNA sequences
                              (sep_5s.fasta, sep_5_8s.fasta, sep_18s.fasta,
                              sep_28s.fasta) generated by myco_rprobe_multi.sh.
  -t <threads>                Number of CPU threads (e.g., 4).
  -o <output_dir>             Output directory path (e.g., 'mapping').
  -m <mirror_path>            Path to the Singularity image file.

Optional arguments:
  -h                          Show this help message and exit.

Examples:
  bash myco_rprobe_evaluate.sh -g example/batch_lib_config.tsv -t 10 \\
      -o batch_mapping -m /path/to/image.sif -r pathgen_fungi
EOF
    exit 1
}

# -----------------------------------------------------------------------------
# Initialize variables
# -----------------------------------------------------------------------------
GENOME_LIST=""
RRNA_DIR=""
THREADS=""
OUTPUT_DIR=""
MIRROR_PATH=""

# -----------------------------------------------------------------------------
# Parse command-line arguments
# -----------------------------------------------------------------------------
while getopts ":r:g:t:o:m:h" opt; do
    case $opt in
        r)  RRNA_DIR="$OPTARG" ;;
        g)  GENOME_LIST="$OPTARG" ;;
        t)  THREADS="$OPTARG" ;;
        o)  OUTPUT_DIR="$OPTARG" ;;
        m)  MIRROR_PATH="$OPTARG" ;;
        h)  usage ;;
        \?) echo "Error: Invalid option -$OPTARG" >&2; usage ;;
        :)  echo "Error: Option -$OPTARG requires an argument." >&2; usage ;;
    esac
done

# -----------------------------------------------------------------------------
# Validate arguments
# -----------------------------------------------------------------------------
if [[ -z "$GENOME_LIST" || -z "$RRNA_DIR" || -z "$THREADS" || -z "$OUTPUT_DIR" || -z "$MIRROR_PATH" ]]; then
    echo "Error: Missing required arguments." >&2
    usage
fi

if [[ ! -e "$RRNA_DIR" ]]; then
    echo "Error: rRNA directory '$RRNA_DIR' does not exist." >&2
    exit 1
fi
if [[ ! -f "$GENOME_LIST" ]]; then
    echo "Error: Genome list file '$GENOME_LIST' does not exist." >&2
    exit 1
fi
if ! [[ "$THREADS" =~ ^[0-9]+$ ]] || [[ "$THREADS" -le 0 ]]; then
    echo "Error: Threads must be a positive integer." >&2
    exit 1
fi
if [[ ! -f "$MIRROR_PATH" ]]; then
    echo "Error: Singularity file '$MIRROR_PATH' does not exist." >&2
    exit 1
fi

# -----------------------------------------------------------------------------
# Print configuration
# -----------------------------------------------------------------------------
echo "=== Parameters ==="
echo "rRNA Directory     : $RRNA_DIR"
echo "Genome Mapping     : $GENOME_LIST"
echo "Threads            : $THREADS"
echo "Output Directory   : $OUTPUT_DIR"
echo "Mirror PATH        : $MIRROR_PATH"
echo "==================="

# =============================================================================
# File path definitions
# =============================================================================
readonly SIF_CMD="singularity -q exec -B /media --cleanenv $MIRROR_PATH"
readonly SLIVA_18S="data/fungi_sliva_18S.fasta"
readonly SLIVA_28S="data/fungi_sliva_28S.fasta"
readonly SEP_5S="${RRNA_DIR}/sep_5s.fasta"
readonly SEP_5_8S="${RRNA_DIR}/sep_5_8s.fasta"
readonly SEP_18S="${RRNA_DIR}/sep_18s.fasta"
readonly SEP_28S="${RRNA_DIR}/sep_28s.fasta"
readonly COV_STAT_SCRIPT="/media/share/data5/1610305236/Panfungi/script/Myco_rProbe/src/stat_coverage.R"
readonly COV_DIR="$OUTPUT_DIR/coverage"

mkdir -p "$COV_DIR"
mkdir -p "$OUTPUT_DIR/index/rrna/"
mkdir -p "$OUTPUT_DIR/index/genome/"

echo "[$(date '+%F %T')]: Starting probe evaluation..."

# =============================================================================
# STEP 1: Quality control with fastp
# =============================================================================

# -----------------------------------------------------------------------------
# Run fastp for read quality control
#
# Trims and filters raw reads, producing cleaned FastQ files.
#
# Args:
#   $1 - strain_name: strain identifier
#   $2 - strain_prefix: sample prefix
#   $3 - raw1: path to R1 FastQ
#   $4 - raw2: path to R2 FastQ
# Returns:
#   0 on success, 1 on fastp failure
# -----------------------------------------------------------------------------
process_with_fastp() {
    local strain_name="$1"
    local strain_prefix="$2"
    local raw1="$3"
    local raw2="$4"
    local clean_dir="$OUTPUT_DIR/$strain_prefix/0_clean"
    local clean1="$clean_dir/${strain_name}_cleaned_R1.fastq.gz"
    local clean2="$clean_dir/${strain_name}_cleaned_R2.fastq.gz"
    local fastp_log="$clean_dir/${strain_name}_fastp.log"
    local fastp_html="$clean_dir/${strain_name}_fastp.html"

    mkdir -p "$clean_dir"

    if [[ -f "$clean1" && -f "$clean2" ]]; then
        echo "[$(date '+%F %T')]: Cleaned FASTQ already exists for $strain_name, skipping fastp."
        return 0
    fi

    echo "[$(date '+%F %T')]: Running fastp for $strain_name..."
    $SIF_CMD fastp -i "$raw1" -I "$raw2" -o "$clean1" -O "$clean2" \
        --thread "$THREADS" --html "$fastp_html" > "$fastp_log" 2>&1

    if [[ $? -ne 0 ]]; then
        echo "[$(date '+%F %T')]: ERROR: fastp failed for $strain_name." >&2
        return 1
    fi

    echo "[$(date '+%F %T')]: Fastp completed for $strain_name."
    return 0
}

# =============================================================================
# STEP 2: rRNA mapping with Bowtie2
# =============================================================================

# -----------------------------------------------------------------------------
# Map reads to rRNA reference and compute depth
#
# Uses Bowtie2 for alignment, Samtools for BAM conversion and depth.
#
# Args:
#   $1 - strain_name: strain identifier
#   $2 - strain_prefix: sample prefix
#   $3 - fq1: path to cleaned R1
#   $4 - fq2: path to cleaned R2
#   $5 - ridx: Bowtie2 index prefix for rRNA
#   $6 - rrna_type: rRNA type (5S, 5_8S, 18S, 28S)
# Returns:
#   0 on success, 1 on missing BAM
# -----------------------------------------------------------------------------
evaluate_rrna() {
    local strain_name="$1"
    local strain_prefix="$2"
    local fq1="$3"
    local fq2="$4"
    local ridx="$5"
    local rrna_type="$6"
    local rrna_dir="$OUTPUT_DIR/$strain_prefix/1_rrna"
    mkdir -p "$rrna_dir"
    local sam="$rrna_dir/${strain_name}.${rrna_type}.sam"
    local dep="$rrna_dir/${strain_name}.${rrna_type}.depth"
    local bam="$rrna_dir/${strain_name}.${rrna_type}.bam"
    local log="$rrna_dir/${strain_name}.${rrna_type}.log"

    echo "[$(date '+%F %T')]: Bowtie2 mapping for $strain_name ($rrna_type)..."
    $SIF_CMD bowtie2 -p "$THREADS" -x "$ridx" -1 "$fq1" -2 "$fq2" --no-unal -S "$sam" &> "$log"

    $SIF_CMD samtools view -b -@ "$THREADS" "$sam" | $SIF_CMD samtools sort -@ "$THREADS" - -o "$bam"
    $SIF_CMD samtools depth "$bam" > "$dep"

    if [[ -f "$bam" ]]; then
        rm -f "$sam"
    else
        echo "[$(date '+%F %T')]: ERROR: BAM not generated for $strain_name ($rrna_type)." >&2
        return 1
    fi

    echo "[$(date '+%F %T')]: rRNA mapping completed for $strain_name ($rrna_type)."
    return 0
}

# =============================================================================
# STEP 3: Genome mapping for background evaluation
# =============================================================================

# -----------------------------------------------------------------------------
# Map reads to whole genome reference
#
# Args:
#   $1 - strain_name: strain identifier
#   $2 - strain_prefix: sample prefix
#   $3 - fq1: path to R1
#   $4 - fq2: path to R2
#   $5 - genome_index: Bowtie2 genome index prefix
# Returns:
#   0 on success, 1 on missing BAM/sorted BAM
# -----------------------------------------------------------------------------
evaluate_genome() {
    local strain_name="$1"
    local strain_prefix="$2"
    local fq1="$3"
    local fq2="$4"
    local genome_index="$5"
    local genome_dir="$OUTPUT_DIR/$strain_prefix/2_aln"
    mkdir -p "$genome_dir"
    local sam="$genome_dir/${strain_name}.sam"
    local bam="$genome_dir/${strain_name}.bam"
    local sorted_bam="$genome_dir/${strain_name}.sorted.bam"
    local log="$genome_dir/${strain_name}.log"

    echo "[$(date '+%F %T')]: Genome mapping for $strain_name..."
    $SIF_CMD bowtie2 -p "$THREADS" -x "$genome_index" -1 "$fq1" -2 "$fq2" --no-unal -S "$sam" &> "$log"

    if $SIF_CMD samtools view -b -@ "$THREADS" -o "$bam" "$sam"; then
        rm -f "$sam"
    else
        echo "[$(date '+%F %T')]: ERROR: BAM not generated for $strain_name." >&2
        return 1
    fi

    echo "[$(date '+%F %T')]: Sorting BAM for $strain_name..."
    if $SIF_CMD samtools sort -@ "$THREADS" -o "$sorted_bam" "$bam"; then
        rm -f "$bam"
    else
        echo "[$(date '+%F %T')]: ERROR: Failed to sort BAM for $strain_name." >&2
        return 1
    fi

    echo "[$(date '+%F %T')]: Genome mapping completed for $strain_name."
    return 0
}

# =============================================================================
# Main processing loop
# =============================================================================
declare -A RNA_FILES=(
    ["5S"]="${SEP_5S}"
    ["5_8S"]="${SEP_5_8S}"
    ["18S"]="${SEP_18S}"
    ["28S"]="${SEP_28S}"
)

while IFS=$'\t' read -r strain prefix raw1 raw2 genome gtf; do
    if [[ -z "$strain" || -z "$raw1" || -z "$raw2" || -z "$genome" ]]; then
        echo "[$(date '+%F %T')]: ERROR: Insufficient fields in genome list entry." >&2
        continue
    fi

    # Build rRNA indices for each type
    for rna_type in "${!RNA_FILES[@]}"; do
        rna_file="${RNA_FILES[$rna_type]}"
        strain_string=${strain//_/ }

        echo "[$(date '+%F %T')]: Building ${rna_type} index for ${strain}..."

        index_basename="$OUTPUT_DIR/index/rrna/${strain}_${rna_type}"
        if [[ -f "${index_basename}.1.bt2" ]]; then
            echo "[$(date '+%F %T')]: Index for ${rna_type} already exists. Skipping."
        else
            echo "[$(date '+%F %T')]: Building ${rna_type} index..."
            mkdir -p "$OUTPUT_DIR/index/rrna/"
            rna_ref_tmp="$OUTPUT_DIR/index/rrna/${strain}_${rna_type}.tmp.fa"
            rna_ref_dedup="$OUTPUT_DIR/index/rrna/${strain}_${rna_type}.dedup.fa"

            echo "[$(date '+%F %T')]: Step 1/3 - Extracting sequences..."
            $SIF_CMD seqkit grep -p "$strain_string|$strain" -n -r "$rna_file" -o "$rna_ref_tmp"

            echo "[$(date '+%F %T')]: Step 2/3 - Removing duplicates..."
            $SIF_CMD seqkit rmdup -s "$rna_ref_tmp" | $SIF_CMD seqkit rmdup -n -o "$rna_ref_dedup"

            echo "[$(date '+%F %T')]: Step 3/3 - Building Bowtie2 index..."
            $SIF_CMD bowtie2-build --threads "$THREADS" --seed 123 "$rna_ref_dedup" "$index_basename"
            if [[ $? -eq 0 ]]; then
                echo "[$(date '+%F %T')]: Index built successfully."
                rm -f "$rna_ref_tmp"
            else
                echo "[$(date '+%F %T')]: ERROR: Bowtie2 index build failed for ${rna_type}." >&2
                rm -f "$rna_ref_tmp"
            fi
        fi
    done

    # Process reads
    if process_with_fastp "$strain" "$prefix" "$raw1" "$raw2"; then
        clean_dir="$OUTPUT_DIR/$prefix/0_clean"
        clean1="$clean_dir/${strain}_cleaned_R1.fastq.gz"
        clean2="$clean_dir/${strain}_cleaned_R2.fastq.gz"

        # Map to each rRNA reference
        for rna_type in "${!RNA_FILES[@]}"; do
            ridx="$OUTPUT_DIR/index/rrna/${strain}_${rna_type}"
            probe_file="$COV_DIR/${rna_type}.probe.tsv"
            len_file="$COV_DIR/${strain}_${rna_type}.length"

            if evaluate_rrna "$strain" "$prefix" "$clean1" "$clean2" "$ridx" "$rna_type"; then
                echo "[$(date '+%F %T')]: rRNA evaluation done for $strain $rna_type."
            else
                echo "[$(date '+%F %T')]: ERROR: rRNA eval failed for $strain $rna_type." >&2
            fi

            if [[ -f "$probe_file" && -f "$len_file" ]]; then
                echo "[$(date '+%F %T')]: Coverage files already exist, skipping."
            else
                echo "[$(date '+%F %T')]: Generating $rna_type probe position data..."

                # Extract probe position information
                cat "$RRNA_DIR/${rna_type}_"*/rrna_probes.fasta 2>/dev/null | grep "^>" | \
                    sed 's/_sliding:/\t/;s/^>//' > "$probe_file"

                # Compute sequence lengths
                awk '/^>/ {
                    if (seq) {print name "\t" length(seq)}
                    name=substr($0, 2); seq=""
                } !/^>/ {
                    seq=seq $0
                } END {
                    if (seq) {print name "\t" length(seq)}
                }' "$rna_ref_dedup" > "$len_file"
            fi

            # Generate coverage visualization
            echo "[$(date '+%F %T')]: Visualizing $rna_type coverage..."
            $SIF_CMD Rscript "$COV_STAT_SCRIPT" "$OUTPUT_DIR" "$strain" "$prefix" "$rna_type"
        done

        # Map to whole genome
        genome_index="$OUTPUT_DIR/index/genome/$prefix"
        if [[ ! -f "${genome_index}.1.bt2" ]]; then
            echo "[$(date '+%F %T')]: Building genome index for $strain..."
            $SIF_CMD bowtie2-build --threads "$THREADS" --seed 123 "$genome" "$genome_index"
        fi

        if evaluate_genome "$strain" "$prefix" "$clean1" "$clean2" "$genome_index"; then
            echo "[$(date '+%F %T')]: Genome mapping completed for $strain."
        else
            echo "[$(date '+%F %T')]: ERROR: Genome mapping failed for $strain." >&2
        fi
    fi
done < "$GENOME_LIST"

# =============================================================================
# STEP 4: Summary statistics
# =============================================================================
echo "[$(date '+%F %T')]: Computing mapping statistics..."

# Collect rRNA mapping rates
grep -H "overall" "$OUTPUT_DIR"/*/1_rrna/*.log 2>/dev/null | \
    sed -E 's/^(.*):(.*)/\2\t\1/' > "$OUTPUT_DIR/rrna_state.tsv" || true

# Collect genome mapping rates
grep -H "overall" "$OUTPUT_DIR"/*/2_aln/*.log 2>/dev/null | \
    sed -E 's/^(.*):(.*)/\2\t\1/' > "$OUTPUT_DIR/genome_state.tsv" || true

echo "[$(date '+%F %T')]: All strain processing completed."
